# Generated by Django 6.0.6 on 2026-06-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('format', models.CharField(blank=True, max_length=16)),
                ('region_tag', models.CharField(blank=True, max_length=32)),
                ('num_choices', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('question_text', models.TextField(blank=True)),
                ('choices', models.JSONField(default=dict)),
                ('correct_answer', models.CharField(blank=True, max_length=8, null=True)),
                ('is_honeypot', models.BooleanField(default=False)),
            ],
        ),
    ]
