# Generated by Django 6.0.6 on 2026-06-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workeranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_honeypot',
            new_name='is_goldtask',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='question_text',
            new_name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='complexity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
