from django.urls import path

from . import views

urlpatterns = [
    path("", views.landing, name="landing"),
    path("register", views.register, name="register"),
    path("register/verify-worker", views.verify_worker_signup_otp, name="verify_worker_signup_otp"),
    path("register/verify-customer", views.verify_customer_signup_otp, name="verify_customer_signup_otp"),
    path("customer/register", views.customer_register, name="customer_register"),
    path("login", views.login, name="login"),
    path("login/verify", views.verify_login_otp, name="verify_login_otp"),
    path("forgot-password", views.forgot_password, name="forgot_password"),
    path("forgot-password/verify", views.verify_reset_otp, name="verify_reset_otp"),
    path("forgot-password/reset", views.reset_password, name="reset_password"),
    path("logout", views.logout, name="logout"),
    path("settings/", views.settings_page, name="settings"),
    path("settings/username", views.update_username, name="update_username"),
    path("settings/password", views.update_password, name="update_password"),
    path("profile/", views.profile_activity, name="profile_activity"),
    path("profile/preferences/", views.profile_preferences, name="profile_preferences"),
    path("profile/security/", views.profile_security, name="profile_security"),
    path("profile/wallet/", views.profile_wallet, name="profile_wallet"),
    path("worker", views.worker_dashboard, name="worker_dashboard"),
    path("setup/", views.worker_setup, name="worker_setup"),
    path("worker/activity-month/", views.worker_activity_month, name="worker_activity_month"),
    path("history/", views.worker_history, name="worker_history"),
    path("invite/create/", views.create_invite, name="create_invite"),
    path("trophies/", views.trophy_room, name="trophy_room"),
    path("store/", views.store_page, name="store"),
    path("store/buy/", views.buy_badge_view, name="buy_badge"),
    path("tasks", views.tasks, name="tasks"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("customer/", views.customer_dashboard, name="customer_dashboard"),
    path("customer/upload/", views.customer_upload, name="customer_upload"),
    path("customer/projects/<int:pk>/", views.customer_project_detail, name="customer_project_detail"),
    path("admin-tools/projects/", views.projects_list, name="projects"),
    path("admin-tools/projects/create/", views.project_create, name="project_create"),
    path("admin-tools/projects/<int:pk>/edit/", views.project_edit, name="project_edit"),
    path("admin-tools/projects/<int:pk>/delete/", views.project_delete, name="project_delete"),
    path("admin-tools/analytics/", views.analytics, name="analytics"),
    path(
        "admin-tools/question-distribution/",
        views.question_distribution,
        name="question_distribution",
    ),
    path("admin-tools/review-queue/", views.review_queue, name="review_queue"),
    path(
        "admin-tools/review-queue/<int:pk>/resolve/",
        views.resolve_review_item,
        name="resolve_review_item",
    ),
    path("admin-tools/tasks/<int:pk>/", views.admin_task_detail, name="admin_task_detail"),
    path("upload-tasks", views.upload_tasks, name="upload_tasks"),
]
